name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"

      - name: Create bin directory
        run: mkdir -p bin

      - name: Download yt-dlp binaries
        run: |
          curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o bin/yt-dlp
          curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp.exe -o bin/yt-dlp.exe
          chmod +x bin/yt-dlp

      - name: Build for all platforms
        run: |
          GOOS=darwin GOARCH=amd64 go build -o dist/yt2mp3-darwin-amd64
          GOOS=darwin GOARCH=arm64 go build -o dist/yt2mp3-darwin-arm64
          GOOS=windows GOARCH=amd64 go build -o dist/yt2mp3-windows-amd64.exe
          GOOS=linux GOARCH=amd64 go build -o dist/yt2mp3-linux-amd64

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/yt2mp3-darwin-amd64
            dist/yt2mp3-darwin-arm64
            dist/yt2mp3-windows-amd64.exe
            dist/yt2mp3-linux-amd64
